name: _portfolio
description: "My CV"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  vector_math: ^2.1.4
  url_launcher: ^6.3.2
  floaty_nav_bar: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/avatar/
    - assets/image/project/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/font/Rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/font/Rubik/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/font/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/font/Rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/font/Rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/font/Rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/font/Rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/font/Rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Rubik Mono One
      fonts:
        - asset: assets/font/Rubik_Mono_One/RubikMonoOne-Regular.ttf
    - family: Rubik Doodle Shadow
      fonts:
        - asset: assets/font/Rubik_Doodle_Shadow/RubikDoodleShadow-Regular.ttf
